#############################################################################
# Makefile for building: tabloid
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  tabloid.pro
# Template: app
# Command: /usr/local/Qt-5.2.1/bin/qmake -o Makefile tabloid.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/usr/local/Qt-5.2.1/mkspecs/linux-g++ -I. -I. -Isrc -I/usr/local/Qt-5.2.1/include -I/usr/local/Qt-5.2.1/include/QtGui -I/usr/local/Qt-5.2.1/include/QtCore -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Qt-5.2.1/lib
LIBS          = $(SUBLIBS) -laubio -L/usr/local/Qt-5.2.1/lib -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Qt-5.2.1/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/converter.cpp \
		src/measure.cpp \
		src/note.cpp \
		src/parser.cpp \
		src/recorder.cpp \
		src/sheet_music.cpp \
		src/tabloid.cpp 
OBJECTS       = converter.o \
		measure.o \
		note.o \
		parser.o \
		recorder.o \
		sheet_music.o \
		tabloid.o
DIST          = /usr/local/Qt-5.2.1/mkspecs/features/spec_pre.prf \
		/usr/local/Qt-5.2.1/mkspecs/common/shell-unix.conf \
		/usr/local/Qt-5.2.1/mkspecs/common/unix.conf \
		/usr/local/Qt-5.2.1/mkspecs/common/linux.conf \
		/usr/local/Qt-5.2.1/mkspecs/common/gcc-base.conf \
		/usr/local/Qt-5.2.1/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Qt-5.2.1/mkspecs/common/g++-base.conf \
		/usr/local/Qt-5.2.1/mkspecs/common/g++-unix.conf \
		/usr/local/Qt-5.2.1/mkspecs/qconfig.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_declarative.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/features/qt_functions.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/qt_config.prf \
		/usr/local/Qt-5.2.1/mkspecs/linux-g++/qmake.conf \
		/usr/local/Qt-5.2.1/mkspecs/features/spec_post.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/default_pre.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/resolve_config.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/default_post.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/warn_on.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/qt.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/resources.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/moc.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/unix/thread.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/exceptions.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/yacc.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/lex.prf \
		tabloid.pro \
		tabloid.pro
QMAKE_TARGET  = tabloid
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = tabloid


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: tabloid.pro /usr/local/Qt-5.2.1/mkspecs/linux-g++/qmake.conf /usr/local/Qt-5.2.1/mkspecs/features/spec_pre.prf \
		/usr/local/Qt-5.2.1/mkspecs/common/shell-unix.conf \
		/usr/local/Qt-5.2.1/mkspecs/common/unix.conf \
		/usr/local/Qt-5.2.1/mkspecs/common/linux.conf \
		/usr/local/Qt-5.2.1/mkspecs/common/gcc-base.conf \
		/usr/local/Qt-5.2.1/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Qt-5.2.1/mkspecs/common/g++-base.conf \
		/usr/local/Qt-5.2.1/mkspecs/common/g++-unix.conf \
		/usr/local/Qt-5.2.1/mkspecs/qconfig.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_declarative.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Qt-5.2.1/mkspecs/features/qt_functions.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/qt_config.prf \
		/usr/local/Qt-5.2.1/mkspecs/linux-g++/qmake.conf \
		/usr/local/Qt-5.2.1/mkspecs/features/spec_post.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/default_pre.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/resolve_config.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/default_post.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/warn_on.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/qt.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/resources.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/moc.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/unix/thread.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/exceptions.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/yacc.prf \
		/usr/local/Qt-5.2.1/mkspecs/features/lex.prf \
		tabloid.pro \
		/usr/local/Qt-5.2.1/lib/libQt5Gui.prl \
		/usr/local/Qt-5.2.1/lib/libQt5Core.prl
	$(QMAKE) -o Makefile tabloid.pro
/usr/local/Qt-5.2.1/mkspecs/features/spec_pre.prf:
/usr/local/Qt-5.2.1/mkspecs/common/shell-unix.conf:
/usr/local/Qt-5.2.1/mkspecs/common/unix.conf:
/usr/local/Qt-5.2.1/mkspecs/common/linux.conf:
/usr/local/Qt-5.2.1/mkspecs/common/gcc-base.conf:
/usr/local/Qt-5.2.1/mkspecs/common/gcc-base-unix.conf:
/usr/local/Qt-5.2.1/mkspecs/common/g++-base.conf:
/usr/local/Qt-5.2.1/mkspecs/common/g++-unix.conf:
/usr/local/Qt-5.2.1/mkspecs/qconfig.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_core.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_declarative.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_declarative_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_help.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_network.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_script.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_x11extras.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Qt-5.2.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Qt-5.2.1/mkspecs/features/qt_functions.prf:
/usr/local/Qt-5.2.1/mkspecs/features/qt_config.prf:
/usr/local/Qt-5.2.1/mkspecs/linux-g++/qmake.conf:
/usr/local/Qt-5.2.1/mkspecs/features/spec_post.prf:
/usr/local/Qt-5.2.1/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt-5.2.1/mkspecs/features/default_pre.prf:
/usr/local/Qt-5.2.1/mkspecs/features/resolve_config.prf:
/usr/local/Qt-5.2.1/mkspecs/features/default_post.prf:
/usr/local/Qt-5.2.1/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/local/Qt-5.2.1/mkspecs/features/warn_on.prf:
/usr/local/Qt-5.2.1/mkspecs/features/qt.prf:
/usr/local/Qt-5.2.1/mkspecs/features/resources.prf:
/usr/local/Qt-5.2.1/mkspecs/features/moc.prf:
/usr/local/Qt-5.2.1/mkspecs/features/unix/opengl.prf:
/usr/local/Qt-5.2.1/mkspecs/features/unix/thread.prf:
/usr/local/Qt-5.2.1/mkspecs/features/testcase_targets.prf:
/usr/local/Qt-5.2.1/mkspecs/features/exceptions.prf:
/usr/local/Qt-5.2.1/mkspecs/features/yacc.prf:
/usr/local/Qt-5.2.1/mkspecs/features/lex.prf:
tabloid.pro:
/usr/local/Qt-5.2.1/lib/libQt5Gui.prl:
/usr/local/Qt-5.2.1/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile tabloid.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/tabloid1.0.0 || mkdir -p .tmp/tabloid1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/tabloid1.0.0/ && $(COPY_FILE) --parents src/converter.h src/measure.h src/note.h src/parser.h src/recorder.h src/sheet_music.h .tmp/tabloid1.0.0/ && $(COPY_FILE) --parents src/converter.cpp src/measure.cpp src/note.cpp src/parser.cpp src/recorder.cpp src/sheet_music.cpp src/tabloid.cpp .tmp/tabloid1.0.0/ && (cd `dirname .tmp/tabloid1.0.0` && $(TAR) tabloid1.0.0.tar tabloid1.0.0 && $(COMPRESS) tabloid1.0.0.tar) && $(MOVE) `dirname .tmp/tabloid1.0.0`/tabloid1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/tabloid1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

converter.o: src/converter.cpp src/converter.h \
		src/sheet_music.h \
		src/measure.h \
		src/note.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o converter.o src/converter.cpp

measure.o: src/measure.cpp src/measure.h \
		src/note.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o measure.o src/measure.cpp

note.o: src/note.cpp src/note.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o note.o src/note.cpp

parser.o: src/parser.cpp src/measure.h \
		src/note.h \
		src/parser.h \
		src/sheet_music.h \
		src/recorder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parser.o src/parser.cpp

recorder.o: src/recorder.cpp src/note.h \
		src/recorder.h \
		src/measure.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o recorder.o src/recorder.cpp

sheet_music.o: src/sheet_music.cpp src/sheet_music.h \
		src/measure.h \
		src/note.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sheet_music.o src/sheet_music.cpp

tabloid.o: src/tabloid.cpp src/converter.h \
		src/sheet_music.h \
		src/measure.h \
		src/note.h \
		src/parser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tabloid.o src/tabloid.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

